default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: route_development

test:
  <<: *default
  database: route_test

production:
  <<: *default
  database: route_production
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  username: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
